apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: example-grafanadatasource
spec:
  datasources:
    - access: proxy
      editable: false
      secureJsonData:
        token: {{ .Values.datasource.influxdbtoken }}
      name: InfluxDB-CR
      url: 'http://timeseries-service-influxdb2'
      jsonData:
        defaultBucket: {{ .Values.datasource.defaultBucket }} 
        httpMode: POST
        organization: {{ .Values.datasource.organization }} 
        timeInterval: 5s
        version: Flux
      isDefault: true
      version: 1
      type: influxdb
  name: influxdb-datasource.yaml
