apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-bundle
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    {{- include "covid19-issuer.labels" . | nindent 4 }}
data: {}
