apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: example-grafanadatasource
spec:
  datasources:
    - access: proxy
      editable: false
      secureJsonData:
        token: >-
          INFLUXDB_TOKEN
      name: InfluxDB-CR
      url: 'http://timeseries-service-influxdb2'
      jsonData:
        defaultBucket: covid19
        httpMode: POST
        organization: qiot
        timeInterval: 5s
        version: Flux
      isDefault: true
      version: 1
      type: influxdb
  name: influxdb-datasource.yaml
