{
 "title": "InfluxDB-example",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "device", "query": "battagliastation13" }
  ]
 },
 "panels": [
  {
   "title": "Gas",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"covid19\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas\")\r\n  |> filter(fn: (r) => r.name == \"${device}\")\r\n  |> drop(columns: [\"ccode\", \"city\",\"country\",\"latitude\",\"longitude\",\"name\",\"serial\",\"station_id\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pollution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"covid19\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pollution\")\r\n  |> filter(fn: (r) => r.name == \"${device}\")\r\n  |> drop(columns: [\"ccode\", \"city\",\"country\",\"latitude\",\"longitude\",\"name\",\"serial\",\"station_id\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Geolocation",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"covid19\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.name == \"${device}\")\r\n  |> map(fn:(r) => ({ r with _value: float(v: r.latitude) }))\r\n  |> map(fn:(r) => ({ r with _measurement: string(v: \"latitude\") }))\r\n  |> map(fn:(r) => ({ r with _field: string(v: \"latitude\") }))\r\n  |> map(fn:(r) => ({ r with timestamp: time(v: r._time) }))\r\n  |> unique(column: \"timestamp\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"covid19\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.name == \"${device}\")\r\n  |> map(fn:(r) => ({ r with _value: float(v: r.longitude) }))\r\n  |> map(fn:(r) => ({ r with _measurement: string(v: \"longitude\") }))\r\n  |> map(fn:(r) => ({ r with _field: string(v: \"longitude\") }))\r\n  |> map(fn:(r) => ({ r with timestamp: time(v: r._time) }))\r\n  |> unique(column: \"timestamp\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Example InfluxDB metric",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"covid19\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pollution\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gt2_5um\")\r\n  |> filter(fn: (r) => r[\"ccode\"] == \"it\")\r\n  |> filter(fn: (r) => r[\"city\"] == \"Vibo Valentia\")\r\n  |> filter(fn: (r) => r[\"country\"] == \"Italy\")\r\n  |> filter(fn: (r) => r[\"latitude\"] == \"38.6766069\")\r\n  |> filter(fn: (r) => r[\"longitude\"] == \"16.0965282\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${device}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"covid19\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.name == \"${device}\")\r\n  |> map(fn:(r) => ({ r with timestamp: time(v: r._time) }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}