apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.settings.serviceName }}
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.settings.volumeCapacity }}
