apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
  name: {{ .Values.settings.serviceName }}
spec:
  ports:
  - name: postgresql
    nodePort: 0
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: {{ .Values.settings.serviceName }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
